services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./Laravel:/var/www
      - /var/www/vendor
      - /var/www/node_modules
      - /var/www/public/build
      - /var/www/public/hot
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver-crm-erp
    ports:
      - "8000:80"
    volumes:
      - ./Laravel:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - /var/www/public/build
      - /var/www/public/hot
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.3
    container_name: crm-erp-BD
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./Database-persistence:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data: 
